# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontEnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 222)
        Dialog.setMaximumSize(QtCore.QSize(400, 222))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.light = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.light.setMinimumSize(QtCore.QSize(50, 0))
        self.light.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";")
        self.light.setObjectName("light")
        self.horizontalLayout.addWidget(self.light)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 75 12pt \"Amiri\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lightControler = QtWidgets.QSlider(Dialog)
        self.lightControler.setGeometry(QtCore.QRect(10, 110, 381, 22))
        self.lightControler.setOrientation(QtCore.Qt.Horizontal)
        self.lightControler.setObjectName("lightControler")
        self.nightLight = QtWidgets.QPushButton(Dialog)
        self.nightLight.setGeometry(QtCore.QRect(10, 150, 371, 51))
        self.nightLight.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.nightLight.setObjectName("nightLight")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "brightness Controller"))
        self.light.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "الضوء:"))
        self.nightLight.setText(_translate("Dialog", "تفعيل الوضع الليلي"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
